name = "Star-Trail"
author = "Dark2932"
version = "AutoUpdate"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e99e5cf5fb0dd68eb00fcd0cb66f84fc387cc3b2385d2fa469e81efcc282b8e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
