name = "Star-Trail"
author = "Dark2932"
version = "AutoUpdate"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32d273772b35c97073debfa340a43e83cb5b6ccb2a64e3c20b82f1a0a138ede2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
