name = "Star-Trail"
author = "Dark2932"
version = "AutoUpdate"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f8cc08f7f33648f39e4bc48de708c9378780a9a0dbb213dce038bb58b41c3df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
