# remove
minecraft:mushroom_fields > null
biomeswevegone:dead_sea > null
biomeswevegone:weeping_witch_forest > null
hybrid_aquatic:coral_reef > null
hybrid_aquatic:deep_coral_reef > null
hybrid_aquatic:tropical_deep_coral_reef > null
hybrid_aquatic:tropical_river > null
regions_unexplored:ashen_woodland > null
regions_unexplored:baobab_savanna > null
regions_unexplored:orchard > null
regions_unexplored:tropics > null
terralith:alpha_islands > null
terralith:alpha_islands_winter > null
terralith:mirage_isles > null
terralith:skylands_spring > null
terralith:skylands_summer > null
terralith:skylands_autumn > null
terralith:skylands_winter > null
terralith:tropical_jungle > null
terralith:warped_mesa > null

# replace
regions_unexplored:alpha_grove > terralith:moonlight_grove
regions_unexplored:barley_fields > minecraft:flower_forest
terralith:cave/mantle_caves > regions_unexplored:prismachasm
terralith:yellowstone > terralith:moonlight_valley
