# remove
minecraft:mushroom_fields > null
biomeswevegone:dead_sea > null
terralith:mirage_isles > null
terralith:tropical_jungle > null
terralith:warped_mesa > null

# replace
biomeswevegone:weeping_witch_forest > terralith:moonlight_grove
terralith:cave/mantle_caves > regions_unexplored:prismachasm
terralith:alpha_islands > minecraft:flower_forest
terralith:alpha_islands_winter > minecraft:flower_forest
terralith:skylands_spring > minecraft:flower_forest
terralith:skylands_summer > minecraft:flower_forest
terralith:skylands_autumn > minecraft:flower_forest
terralith:skylands_winter > minecraft:flower_forest
terralith:yellowstone > terralith:moonlight_valley
