# remove
minecraft:mushroom_fields > null
biomeswevegone:dead_sea > null
biomeswevegone:weeping_witch_forest > null
regions_unexplored:ashen_woodland > null
regions_unexplored:baobab_savanna > null
regions_unexplored:orchard > null
regions_unexplored:tropics > null
terralith:mirage_isles > null
terralith:warped_mesa > null

# replace
regions_unexplored:alpha_grove > terralith:moonlight_grove
regions_unexplored:barley_fields > minecraft:flower_forest
terralith:alpha_islands > minecraft:flower_forest
terralith:alpha_islands_winter > minecraft:flower_forest
terralith:cave/mantle_caves > regions_unexplored:prismachasm
terralith:skylands > minecraft:flower_forest
terralith:skylands_spring > minecraft:flower_forest
terralith:skylands_summer > minecraft:flower_forest
terralith:skylands_autumn > minecraft:flower_forest
terralith:skylands_winter > minecraft:flower_forest
terralith:yellowstone > terralith:moonlight_valley