#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 21 00:20:56 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=BSL_v10.0.zip
enableShaders=false
